

services:
  travelo-database:
    image: mysql:8.0
    container_name: travelo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: chaima2003
      MYSQL_DATABASE: travelo_db
    volumes:
      - travelo-mysql-data:/var/lib/mysql
    networks:
      - travelo-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pchaima2003"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    container_name: travelo-backend
    build: ./travelo_backend
    depends_on:
      travelo-database:
        condition: service_healthy
    networks:
      - travelo-net

  frontend:
    container_name: travelo-frontend
    build: ./travelo_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - travelo-net

volumes:
  travelo-mysql-data:

networks:
  travelo-net:
    driver: bridge

